### ISSUE TITLE
[bugReport] assertion with refactored main/FileIO code

### ISSUE THREAD

**Issue by Sungju-Huh** [lkwh12/BugKillers#60]
main과 FileIO를 refactoring한 commit e9c29553da801dcd609c471554c3dd1c2643cec8를 적용하면 vector 접근하다가 assertion이 발생합니다. revert하면 발생하지 않는 것을 확인했습니다.
현호님 확인 부탁드리겠습니다~

**Comment by Sungju-Huh** [comment]
https://github.com/lkwh12/BugKillers/pull/63
이전 코드와 diff해본 결과 readLine의 결과가 ""인 경우 break하는 부분이 누락되어 있어
이를 추가하여 1차 수정하였습니다.

**Comment by h2kfl** [comment]
이슈로 문제가 관리되니 누락되지 않고 처리가 가능하네요.
#63 에서 수정 확인하였습니다.
별도로 #62 에서 string 반환하며 객체 재생성되는 부분을 개선하면서 빈 줄은 처리하지 않도록 변경하였습니다.
